// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6nwLXMC0t4vpul37wCu0H4qHiGnDHVpY',
    appId: '1:633729870666:web:a4c622ec706a5b82cdefb3',
    messagingSenderId: '633729870666',
    projectId: 'learning-flutter-6aa30',
    authDomain: 'learning-flutter-6aa30.firebaseapp.com',
    storageBucket: 'learning-flutter-6aa30.appspot.com',
    measurementId: 'G-D365BEW2JJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd0-BB5qSXk2jWgtP_X4VD-noJ2LOWaos',
    appId: '1:633729870666:android:812409ff6484f47ecdefb3',
    messagingSenderId: '633729870666',
    projectId: 'learning-flutter-6aa30',
    storageBucket: 'learning-flutter-6aa30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFINXL9ega3HHQR3RrJqept4rPnqJ21D8',
    appId: '1:633729870666:ios:6619386e19d12fffcdefb3',
    messagingSenderId: '633729870666',
    projectId: 'learning-flutter-6aa30',
    storageBucket: 'learning-flutter-6aa30.appspot.com',
    iosBundleId: 'com.example.learningFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFINXL9ega3HHQR3RrJqept4rPnqJ21D8',
    appId: '1:633729870666:ios:cd533c1db903d77dcdefb3',
    messagingSenderId: '633729870666',
    projectId: 'learning-flutter-6aa30',
    storageBucket: 'learning-flutter-6aa30.appspot.com',
    iosBundleId: 'com.example.learningFlutter.RunnerTests',
  );
}
